### ISSUE TITLE
Tracebacks

### ISSUE THREAD

**Issue by zmwangx** [zmwangx/pyonedrive#24]
This issue is supposed to collect some unresolved tracebacks that I might investigate in the future.

**Comment by zmwangx** [comment]
Version: 390bcb65259400545dab3f2366ed37d97596cefe

``` python-traceback
Traceback (most recent call last):
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/ssl.py", line 751, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/ssl.py", line 623, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 304, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.onedrive.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zmwang/.pyenv/versions/3.4.3/bin/onedrive-mv", line 9, in <module>
    load_entry_point('onedrive==0.1.dev0', 'console_scripts', 'onedrive-mv')()
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/cli.py", line 778, in cli_mv
    return cli_mv_or_cp("mv", "onedrive-mv")
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/cli.py", line 716, in cli_mv_or_cp
    if client.isdir(args.paths[1]):
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/api.py", line 700, in isdir
    self.assert_dir(path)
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/api.py", line 642, in assert_dir
    metadata = self.metadata(path)
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/api.py", line 571, in metadata
    metadata_response = self.get("drive/root:/%s" % encoded_path)
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/auth.py", line 229, in get
    return self.request("get", url, params=params, **kwargs)
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/auth.py", line 217, in request
    response = self.request(method, url, noretry=True, **kwargs)
  File "/Users/zmwang/dev/src/py/onedrive/onedrive/auth.py", line 203, in request
    response = self.client.request(method, url, **kwargs)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/zmwang/.pyenv/versions/3.4.3/lib/python3.4/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.onedrive.com', port=443): Read timed out. (read timeout=10)
```

Might be related: https://github.com/kennethreitz/requests/issues/1915

I'm not concerned about this issue at the moment, since this is my first encounter ever.
